version: '3'

services:
  #Producer to obtain data from RTSP and write into Kafka queue
  producer:
    image: producer
    container_name: producer   
    environment:
      - TOPICNAME=test
      - KAFKAPORT=kafka:9093
      - RTSPLINK=rtsp://freja.hiof.no:1935/rtplive/_definst_/hessdalen03.stream
        # Image format = RGBA, uint8
        # Num of channels = 3
        # Total pixels = 38400
        # Image size = [160 240]
        # Num of rows = 160
        # Num of cols = 240
    networks:
      - full_app_dockerNet
        # To ensure that the containers in different docker-compose files communicate with each other, we place them on the same network. The complete network name is 'zookeeper_dockerNet'. It is derived by joining the name of the folder from which the network originates (i.e., zookeeper) and the name of the network (i.e., dockerNet).
    privileged: true  

networks:
  full_app_dockerNet:
    external: true #Label the other docker-compose network as an external network to the current docker-compose file

